### ISSUE TITLE
demo website for others to fork

### ISSUE THREAD

**Issue by medewitt** [WFU-TLC/default_website#1]
@francojc @francojc @johnstc can you all review this site? It is pretty bare bones but it at least gives the participants a place to start and we can hook it up to github pages. 

Main structure
- Course Notes
- Pre - Work
- Project

And as we build competency I imagine us growing/ customising

**Comment by medewitt** [comment]
if you want to see it rendered here it is :[here](http://users.wfu.edu/dewittme/)

**Comment by francojc** [comment]
I think it looks really good. I like the three tabbed sections and the splash page is very informative. 

One typo in the 'index.Rmd' file: 

'You can use this page to give introductions about what your are doing **amd** your aims.'

Otherwise it looks good to merge!

**Comment by brown-allen** [comment]
Looks great. Thanks to both of you for all this work.

**Comment by medewitt** [comment]
Going to go ahead and close this with #2
